begin;

create temporary table new_rules_question_batch (
  authoring_id integer primary key,
  question_text text not null,
  category text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null,
  explanation text not null,
  difficulty_level text not null,
  is_frequently_tested boolean not null,
  subcategory text not null,
  learning_topic text not null,
  handbook_section text not null,
  handbook_url text not null
) on commit drop;

insert into new_rules_question_batch
select *
from jsonb_to_recordset($question_bank$
[
  {"authoring_id":1,"question_text":"What is the minimum age to apply for an Ontario driver's licence?","category":"Licence Eligibility","option_a":"16 years old","option_b":"15 years old","option_c":"17 years old","option_d":"18 years old","correct_option":"A","explanation":"Ontario residents must be at least 16 years old to apply for a driver's licence.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Application requirements","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":2,"question_text":"After becoming an Ontario resident, how long may you generally use your existing out-of-province licence while applying for an Ontario licence?","category":"New Ontario Residents","option_a":"30 days","option_b":"60 days","option_c":"90 days","option_d":"Six months","correct_option":"B","explanation":"A new Ontario resident generally has 60 days to continue using an existing valid licence and apply for an Ontario licence.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Licence exchange","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":3,"question_text":"How can an eligible G1 driver reduce the usual 12-month Level One waiting period before taking the first road test?","category":"Graduated Licensing","option_a":"Drive only during daylight hours","option_b":"Complete 100 hours of unsupervised driving","option_c":"Complete an approved beginner driver education course, reducing the period to eight months","option_d":"Pass a second written knowledge test","correct_option":"C","explanation":"Completing an approved beginner driver education course can reduce Level One from 12 months to eight months.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"G1 waiting period","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":4,"question_text":"Where must the accompanying driver sit while supervising a G1 driver?","category":"G1 Supervision","option_a":"In any rear seat","option_b":"In the rear seat behind the driver","option_c":"In either front or rear seat","option_d":"In the front passenger seat","correct_option":"D","explanation":"The accompanying driver must sit in the front passenger seat, and is the only person permitted in the front seat with the G1 driver.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Accompanying driver position","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":5,"question_text":"When may a G1 driver practise on a road that is otherwise prohibited because it is a high-speed expressway?","category":"G1 Restrictions","option_a":"When the accompanying driver is a qualified driving instructor","option_b":"Whenever traffic is light","option_c":"Only on weekends","option_d":"After holding a G1 licence for six months","correct_option":"A","explanation":"A G1 driver may drive on otherwise prohibited high-speed roads when the accompanying driver is a qualified driving instructor.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Highway restriction exception","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":6,"question_text":"What kind of identification documents must normally be presented when applying for an Ontario driver's licence?","category":"Licence Application","option_a":"Photocopies certified by a friend","option_b":"Original, valid documents showing legal name and complete date of birth","option_c":"Expired documents bearing a photograph","option_d":"Digital screenshots of identity documents","correct_option":"B","explanation":"Licence applicants must normally present original, valid documents. Photocopies and expired documents are not accepted.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Proof of identity","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":7,"question_text":"How long must a driver normally remain at Level Two before attempting the road test for a full Class G licence?","category":"G2 Licence","option_a":"Six months","option_b":"Eight months","option_c":"At least 12 months","option_d":"At least 24 months","correct_option":"C","explanation":"Level Two lasts at least 12 months before the driver may take the road test for full Class G privileges.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"G2 waiting period","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":8,"question_text":"Which situation exempts a G2 driver aged 19 or under from the overnight young-passenger limit?","category":"G2 Restrictions","option_a":"The trip is shorter than 20 kilometres","option_b":"The driver has held G2 for three months","option_c":"Every passenger has a seatbelt","option_d":"A fully licensed driver is in the front passenger seat or the passengers are immediate family","correct_option":"D","explanation":"The overnight young-passenger restriction does not apply when a fully licensed driver is in the front passenger seat or the young passengers are immediate family.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Passenger restriction exemptions","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":9,"question_text":"How many road tests must a new Class G driver pass to progress from G1 to a full G licence?","category":"Graduated Licensing","option_a":"Two road tests","option_b":"One road test","option_c":"Three road tests","option_d":"No road tests if driver education is completed","correct_option":"A","explanation":"A new driver must pass one road test to move from G1 to G2 and a second road test to obtain full Class G privileges.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Road-test progression","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},
  {"authoring_id":10,"question_text":"What seatbelt condition applies while a G1 driver is operating a vehicle?","category":"G1 Restrictions","option_a":"Only front-seat occupants need working seatbelts","option_b":"Every person in the vehicle must have a working seatbelt","option_c":"Seatbelts are optional below 50 km/h","option_d":"Only the G1 driver and supervisor need seatbelts","correct_option":"B","explanation":"A G1 driver may drive only when every person in the vehicle has a working seatbelt.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Occupant restraints","learning_topic":"Licensing and responsibilities","handbook_section":"Getting your driver's licence","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/getting-your-drivers-licence"},

  {"authoring_id":11,"question_text":"What should you do if illness, fatigue or strong emotion makes it difficult to concentrate on driving?","category":"Driver Fitness","option_a":"Drive faster to shorten the trip","option_b":"Use cruise control and continue","option_c":"Avoid driving until you can give the task your full attention","option_d":"Open a window and ignore the symptoms","correct_option":"C","explanation":"Safe driving requires physical and mental alertness. Do not drive when your condition prevents full concentration.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Physical and mental readiness","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":12,"question_text":"How should the driver's seat be adjusted before moving the vehicle?","category":"Driving Position","option_a":"As far back as possible, even if pedals are difficult to reach","option_b":"Low enough that the road is barely visible","option_c":"Close enough that the driver's chest touches the wheel","option_d":"So the pedals and controls can be reached comfortably while maintaining a clear view","correct_option":"D","explanation":"Adjust the seat so you can reach the pedals and controls comfortably, steer properly and see clearly in all directions.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Seat adjustment","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":13,"question_text":"Where should the lap portion of a seatbelt fit?","category":"Seatbelts","option_a":"Low and snug across the hips","option_b":"Across the stomach","option_c":"Under one arm","option_d":"Loosely across the thighs","correct_option":"A","explanation":"The lap belt should fit low and snug across the hips, while the shoulder belt crosses the chest and shoulder.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Proper belt fit","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":14,"question_text":"How should a vehicle's head restraint normally be positioned?","category":"Occupant Protection","option_a":"Below shoulder level","option_b":"With its top at about the top of the occupant's ears","option_c":"Against the middle of the back","option_d":"As low as the adjustment allows","correct_option":"B","explanation":"A properly adjusted head restraint has its top at about the top of the occupant's ears and is close behind the head.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Head restraints","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":15,"question_text":"Why must a rear-facing child car seat never be placed in front of an active airbag?","category":"Child Safety","option_a":"It blocks the driver's mirror","option_b":"It makes the seatbelt too loose","option_c":"An inflating airbag can strike the seat and seriously injure the child","option_d":"It prevents the passenger door from opening","correct_option":"C","explanation":"A deploying front airbag can hit a rear-facing child seat with great force, causing serious or fatal injury.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Airbags and child seats","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":16,"question_text":"Where is the safest place in most vehicles for children under age 13?","category":"Child Safety","option_a":"The front passenger seat","option_b":"Any seat without a head restraint","option_c":"The cargo area of a hatchback","option_d":"The rear seat, properly restrained","correct_option":"D","explanation":"Children under 13 are safest in the rear seat when secured in the restraint appropriate for their size and age.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Seating position","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":17,"question_text":"When must a vehicle's full lighting system generally be turned on around sunset and sunrise?","category":"Vehicle Lighting","option_a":"From one-half hour before sunset until one-half hour after sunrise","option_b":"Only after complete darkness","option_c":"From sunset until sunrise exactly","option_d":"Only when streetlights turn on","correct_option":"A","explanation":"The handbook requires the full lighting system from one-half hour before sunset until one-half hour after sunrise and whenever visibility is poor.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Required lighting times","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":18,"question_text":"When should you use the horn while driving?","category":"Communication","option_a":"To express annoyance","option_b":"Only when reasonably necessary to warn another road user","option_c":"Whenever entering an intersection","option_d":"To tell a slow driver to speed up","correct_option":"B","explanation":"Use the horn only when reasonably necessary as a warning. It should not be used to express anger or impatience.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Horn use","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":19,"question_text":"Why should a driver keep looking well ahead instead of focusing only on the vehicle directly in front?","category":"Observation","option_a":"To avoid checking mirrors","option_b":"To make the road appear wider","option_c":"To identify hazards early and make smooth, planned adjustments","option_d":"To eliminate the need for a following distance","correct_option":"C","explanation":"Looking well ahead helps a driver detect developing hazards early and adjust speed or position smoothly.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Visual scanning","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":20,"question_text":"Why should a driver avoid sitting too close to the steering wheel?","category":"Occupant Protection","option_a":"It increases fuel consumption","option_b":"It prevents mirror adjustment","option_c":"It makes turn signals harder to hear","option_d":"It reduces the safe space available for the airbag to deploy","correct_option":"D","explanation":"Adequate distance from the steering wheel allows the airbag to deploy as designed and reduces injury risk.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"Airbag clearance","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":21,"question_text":"What should be done with snow, ice or dirt that obstructs vehicle windows, mirrors or lights?","category":"Pre-Drive Inspection","option_a":"Remove it before driving","option_b":"Wait for airflow to remove it","option_c":"Clear only a small area of the windshield","option_d":"Drive slowly until it falls away","correct_option":"A","explanation":"Before driving, clear windows, mirrors and lights so you can see and other road users can see your signals and vehicle.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Visibility checks","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":22,"question_text":"Why should loose objects be secured inside a vehicle?","category":"Vehicle Safety","option_a":"They make the engine work harder","option_b":"They can become dangerous projectiles during sudden braking or a collision","option_c":"They interfere with the vehicle's paint","option_d":"They cause tires to lose pressure","correct_option":"B","explanation":"Loose objects can fly through the passenger compartment during hard braking or a collision and injure occupants.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Cargo in passenger compartment","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":23,"question_text":"What is the safest footwear choice for driving?","category":"Vehicle Control","option_a":"Bare feet whenever possible","option_b":"Loose sandals that can be removed quickly","option_c":"Secure footwear that allows reliable pedal control","option_d":"Heavy boots that prevent ankle movement","correct_option":"C","explanation":"Wear secure footwear that permits accurate use of the pedals and cannot slip off or become caught underneath them.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Pedal operation","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":24,"question_text":"What should you do immediately before getting into a parked vehicle?","category":"Pre-Drive Inspection","option_a":"Sound the horn twice","option_b":"Start the engine from outside","option_c":"Check only the driver's-side tire","option_d":"Walk around it and check for children, obstacles, damage or other hazards","correct_option":"D","explanation":"A quick walk-around can reveal children, objects, fluid leaks, tire problems or other hazards that may not be visible from the driver's seat.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Vehicle walk-around","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":25,"question_text":"If another driver follows you and behaves threateningly, what is the safest response?","category":"Road Rage","option_a":"Keep the doors locked, avoid driving home and go to a police station or busy public place","option_b":"Stop in an isolated area to speak with the driver","option_c":"Lead the driver to your home","option_d":"Retaliate so the driver backs away","correct_option":"A","explanation":"If threatened, remain in the locked vehicle, avoid confrontation and drive to police or a busy public place rather than going home.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Threat response","learning_topic":"Safe and responsible driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},

  {"authoring_id":26,"question_text":"How should a driver treat a cyclist who is legally using a traffic lane?","category":"Cyclists","option_a":"Force the cyclist onto the sidewalk","option_b":"Recognize the cyclist's right to the lane and pass only when it is safe","option_c":"Sound the horn continuously until the cyclist stops","option_d":"Pass within the same lane regardless of space","correct_option":"B","explanation":"Cyclists are road users with legal rights and responsibilities. Give them room and pass only when it can be done safely.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Cyclist lane rights","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":27,"question_text":"Before opening a vehicle door beside moving traffic, what should you do?","category":"Cyclists","option_a":"Rely only on the passenger to warn you","option_b":"Open the door slightly to make cyclists move over","option_c":"Check mirrors and the blind spot for cyclists and other traffic","option_d":"Sound the horn before opening","correct_option":"C","explanation":"Check mirrors and over your shoulder before opening a door so you do not strike a cyclist or force one into traffic.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Dooring prevention","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":28,"question_text":"When preparing to turn right across the path of a cyclist travelling beside you, what should you do?","category":"Cyclists","option_a":"Accelerate and turn in front of the cyclist","option_b":"Move into the bicycle lane without checking","option_c":"Use the horn to require the cyclist to stop","option_d":"Yield and turn only after the cyclist's path is clear","correct_option":"D","explanation":"Do not cut off a cyclist when turning. Check carefully, yield as required and turn only when the cyclist's path is clear.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Right turns across cyclists","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":29,"question_text":"Why should you scan carefully for cyclists at intersections?","category":"Cyclists","option_a":"Their smaller size can make them difficult to see","option_b":"Cyclists must always stop for motor vehicles","option_c":"Cyclists are required to use sidewalks","option_d":"Cyclists cannot travel through intersections","correct_option":"A","explanation":"Cyclists are smaller and may be hidden by vehicles, roadside objects or blind spots, so look carefully before proceeding or turning.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Cyclist visibility","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":30,"question_text":"When may a motor vehicle enter a bicycle lane?","category":"Bicycle Lanes","option_a":"Whenever traffic is congested","option_b":"Only where permitted and necessary for a turn or access, after checking and yielding","option_c":"To pass a vehicle on the right","option_d":"To stop briefly while loading passengers","correct_option":"B","explanation":"Bicycle lanes are reserved for cyclists. Cross or enter one only where permitted for a turn or access, after checking for and yielding to cyclists.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Bike-lane crossings","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":31,"question_text":"How much of a traffic lane is a motorcyclist entitled to use?","category":"Motorcycles","option_a":"Only the right-hand third","option_b":"Only the portion not used by cars","option_c":"The full lane","option_d":"The shoulder whenever one exists","correct_option":"C","explanation":"A motorcycle is entitled to the full lane. Never try to share the lane while passing a motorcyclist.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Motorcycle lane position","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":32,"question_text":"Why should you not rely solely on a motorcycle's flashing turn signal?","category":"Motorcycles","option_a":"Motorcycle signals are always decorative","option_b":"Motorcyclists are prohibited from turning at intersections","option_c":"A motorcycle signal always means the rider is stopping","option_d":"Some motorcycle signals do not cancel automatically, so confirm the rider's movement","correct_option":"D","explanation":"Some motorcycle turn signals remain flashing after a turn. Wait for clear evidence of the rider's intended movement.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"Turn-signal awareness","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":33,"question_text":"What happens to a large truck's blind spots as the truck becomes longer and wider?","category":"Large Vehicles","option_a":"They generally become larger","option_b":"They disappear behind the trailer","option_c":"They remain identical to a car's blind spots","option_d":"They exist only on the driver's side","correct_option":"A","explanation":"Large commercial vehicles have substantial blind spots, and those areas generally increase with the vehicle's length and width.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Truck blind spots","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":34,"question_text":"After passing a large truck, why should you leave extra space before returning to its lane?","category":"Large Vehicles","option_a":"Trucks accelerate faster than cars","option_b":"Cutting in reduces the truck driver's stopping space and may place you in a blind spot","option_c":"Truck headlights cannot use low beams","option_d":"Large trucks are required to change lanes after being passed","correct_option":"B","explanation":"Large vehicles need more stopping distance. Returning too soon removes their safety margin and may put your vehicle where the truck driver cannot see it.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Passing trucks","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":35,"question_text":"What should you do when a municipal bus signals that it is leaving a bus bay?","category":"Municipal Buses","option_a":"Speed up before the bus enters","option_b":"Move onto the shoulder","option_c":"Slow down and yield so the bus can re-enter traffic safely","option_d":"Stop beside the bus and wait for a hand signal","correct_option":"C","explanation":"Drivers must yield to a municipal bus signalling its intention to re-enter traffic from a designated bus bay.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Bus-bay merging","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":36,"question_text":"At a streetcar stop without a safety island, what must you confirm before moving after the doors close?","category":"Streetcars","option_a":"That the streetcar driver has sounded the horn","option_b":"That another car has already passed","option_c":"That the traffic light ahead is green","option_d":"That passengers have safely reached the curb and the way is clear","correct_option":"D","explanation":"After stopping behind the rear doors at a stop without a safety island, proceed only when the doors are closed, passengers have reached the curb and the way is clear.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Resuming after passenger loading","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":37,"question_text":"What does the slow-moving vehicle sign on farm equipment indicate?","category":"Farm Vehicles","option_a":"The vehicle is designed to travel at 40 km/h or less","option_b":"The vehicle may use only private property","option_c":"The vehicle will always turn left","option_d":"The vehicle is carrying dangerous goods","correct_option":"A","explanation":"The orange-and-red slow-moving vehicle sign identifies a vehicle designed to travel at 40 km/h or less.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Slow-moving vehicle emblem","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":38,"question_text":"How should you pass a horse and rider on the roadway?","category":"Horse-Drawn and Horse-Ridden Vehicles","option_a":"Sound the horn continuously","option_b":"Slow down, leave plenty of room and avoid frightening the horse","option_c":"Pass as closely as possible at steady speed","option_d":"Rev the engine to warn the rider","correct_option":"B","explanation":"Horses can be startled by noise or sudden movement. Slow down, provide a wide space and pass quietly when safe.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Passing horses","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":39,"question_text":"What do a school bus's flashing amber lights tell approaching drivers?","category":"School Buses","option_a":"The bus is out of service","option_b":"The bus may be passed immediately","option_c":"The bus is preparing to stop, so slow down and prepare to stop","option_d":"Only traffic behind the bus must react","correct_option":"C","explanation":"Flashing amber lights warn that the school bus is preparing to stop. Approach cautiously and be ready to stop.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Amber warning lights","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},
  {"authoring_id":40,"question_text":"On a highway divided by a median, who must stop for a school bus displaying flashing red lights?","category":"School Buses","option_a":"Traffic in both directions, including across the median","option_b":"Only traffic approaching from behind in the far-left lane","option_c":"Only vehicles travelling toward the bus from the opposite roadway","option_d":"Traffic travelling in the same direction as the bus; traffic on the opposite roadway is not required to stop","correct_option":"D","explanation":"On a highway separated by a median, only traffic travelling on the same roadway and in the same direction as the bus must stop.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Divided-highway stopping","learning_topic":"Sharing the road","handbook_section":"Sharing the road with other road users","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/sharing-road-other-road-users"},

  {"authoring_id":41,"question_text":"What controls right-of-way at a controlled intersection?","category":"Controlled Intersections","option_a":"Traffic lights, signs or a traffic-control person","option_b":"The size of each vehicle","option_c":"The speed of approaching traffic","option_d":"The direction with the most lanes","correct_option":"A","explanation":"A controlled intersection uses traffic lights, signs or a traffic-control person. Drivers must obey the applicable control.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Intersection controls","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":42,"question_text":"At an uncontrolled intersection, what normally happens when one vehicle arrives clearly before another?","category":"Uncontrolled Intersections","option_a":"The later vehicle goes first","option_b":"The vehicle that arrived first proceeds first after checking that it is safe","option_c":"The larger vehicle goes first","option_d":"Both vehicles proceed together","correct_option":"B","explanation":"At an uncontrolled intersection, the vehicle that arrives first normally has priority, but its driver must still ensure the way is safe.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Arrival order","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":43,"question_text":"Two vehicles reach an uncontrolled intersection at the same time. Which driver should yield?","category":"Uncontrolled Intersections","option_a":"The driver on the right","option_b":"The driver travelling faster","option_c":"The driver on the left yields to the driver on the right","option_d":"The driver going straight","correct_option":"C","explanation":"When vehicles arrive at an uncontrolled intersection at the same time, the driver on the left must yield to the driver on the right.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Yield-to-the-right rule","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":44,"question_text":"Where should you stop at a stop sign when there is no marked stop line?","category":"Stop Signs","option_a":"In the middle of the crosswalk","option_b":"After entering the intersection","option_c":"Beside the stop sign regardless of the roadway edge","option_d":"Before the crosswalk or sidewalk; if neither exists, at the edge of the intersection","correct_option":"D","explanation":"Stop at the marked line when one exists. Without a line, stop before the crosswalk or sidewalk, or otherwise at the edge of the intersection where you can check safely.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Stopping position","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":45,"question_text":"At a pedestrian crossover, when may a stopped driver proceed?","category":"Pedestrian Crossovers","option_a":"After pedestrians and the school crossing guard, if present, have completely crossed and cleared the roadway","option_b":"As soon as the pedestrian passes the centre line","option_c":"When another driver begins moving","option_d":"After sounding the horn","correct_option":"A","explanation":"Remain stopped at a pedestrian crossover until pedestrians and any crossing guard have completely crossed and cleared the roadway.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Complete crossing requirement","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":46,"question_text":"What must you do when a school crossing guard displays a stop sign?","category":"School Crossings","option_a":"Proceed if no child is directly ahead","option_b":"Stop and remain stopped until everyone, including the guard, has cleared the roadway","option_c":"Pass the guard at walking speed","option_d":"Stop only if the traffic light is red","correct_option":"B","explanation":"Drivers must obey a school crossing guard's stop sign and remain stopped until the guard and all pedestrians are safely off the roadway.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Crossing-guard directions","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":47,"question_text":"When railway signals require you to stop, how far from the nearest rail should you stop?","category":"Railway Crossings","option_a":"At least one metre","option_b":"Exactly three metres","option_c":"At least five metres","option_d":"At least 20 metres","correct_option":"C","explanation":"Stop at least five metres from the nearest rail when warning signals, gates or an approaching train require a stop.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Stopping position","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":48,"question_text":"What should you do when the gates at a railway crossing are lowered?","category":"Railway Crossings","option_a":"Drive around the gate if no train is visible","option_b":"Stop on the tracks to look both ways","option_c":"Follow another vehicle around the gate","option_d":"Stop and wait; never drive around or under the gate","correct_option":"D","explanation":"A lowered railway gate must never be driven around or under. Wait until the gate rises and all warnings stop before proceeding safely.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Crossing gates","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":49,"question_text":"If your vehicle stalls on railway tracks and a train may be approaching, what is the first priority?","category":"Railway Crossings","option_a":"Get everyone out, move well away from the tracks and call emergency services","option_b":"Stay inside with seatbelts fastened","option_c":"Try repeatedly to restart until the train is close","option_d":"Stand directly beside the vehicle to signal the train","correct_option":"A","explanation":"Evacuate immediately and move everyone a safe distance away from the tracks, then call 911 or the railway emergency number.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"Vehicle stalled on tracks","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":50,"question_text":"How far away should you stop when approaching a school bus with its upper red lights flashing?","category":"School Buses","option_a":"At least five metres","option_b":"At least 20 metres","option_c":"One car length","option_d":"At the rear bumper","correct_option":"B","explanation":"Stop at least 20 metres away from a school bus displaying its upper red lights and stop arm.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Stopping distance","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":51,"question_text":"After stopping for a school bus with flashing red lights, when may you proceed?","category":"School Buses","option_a":"As soon as the last visible child reaches the curb","option_b":"When the vehicle behind you sounds its horn","option_c":"When the red lights stop flashing, the stop arm folds away and the bus begins to move","option_d":"After waiting exactly 30 seconds","correct_option":"C","explanation":"Remain stopped until the bus's red lights stop flashing, the stop arm retracts and the bus moves or the driver signals traffic to proceed.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Resuming after a stop","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":52,"question_text":"What does a flashing raised-hand pedestrian signal mean to a pedestrian who has not started crossing?","category":"Pedestrian Signals","option_a":"Begin crossing quickly","option_b":"Cross only halfway","option_c":"Traffic must reverse direction","option_d":"Do not start crossing; pedestrians already crossing should finish safely","correct_option":"D","explanation":"A flashing raised hand warns pedestrians not to begin crossing. Anyone already in the crossing should continue and clear it safely.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Flashing hand signal","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":53,"question_text":"Whose directions take priority when a police officer is controlling traffic at an intersection?","category":"Traffic Control","option_a":"The police officer's directions","option_b":"The traffic light in every case","option_c":"The nearest driver's hand signal","option_d":"The usual right-of-way rule only","correct_option":"A","explanation":"A driver must obey a police officer or authorized traffic-control person's directions even when they differ from lights or signs.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Officer directions","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":54,"question_text":"What should you do if an emergency vehicle approaches while you are already inside an intersection?","category":"Emergency Vehicles at Intersections","option_a":"Stop immediately in the intersection","option_b":"Clear the intersection safely, then pull over and stop","option_c":"Reverse to the stop line","option_d":"Turn toward the emergency vehicle","correct_option":"B","explanation":"Do not block the intersection. Proceed through it safely, then move to the appropriate edge of the road and stop.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Clearing intersections","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},
  {"authoring_id":55,"question_text":"Before crossing railway tracks, why should you make sure there is enough space beyond them?","category":"Railway Crossings","option_a":"To improve fuel economy","option_b":"To allow another vehicle to pass on the tracks","option_c":"So your vehicle will not have to stop with any part of it on the tracks","option_d":"So you can change lanes while crossing","correct_option":"C","explanation":"Never enter a railway crossing unless there is enough room beyond it for your entire vehicle to clear the tracks.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Space beyond tracks","learning_topic":"Intersections, signs and signals","handbook_section":"Driving through intersections","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/driving-through-intersections"},

  {"authoring_id":56,"question_text":"After passing another vehicle, when is it generally safe to return to the original lane?","category":"Passing","option_a":"As soon as your front bumper is ahead","option_b":"When the other driver flashes headlights","option_c":"Immediately after signalling","option_d":"When you can see the entire front of the passed vehicle in your inside mirror","correct_option":"D","explanation":"Seeing the entire front of the passed vehicle in your inside mirror indicates that you have enough space to return without cutting it off.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Returning after a pass","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":57,"question_text":"What should you do if the vehicle you are passing speeds up?","category":"Passing","option_a":"Do not race; return to your original lane when it is safe","option_b":"Exceed the speed limit to finish passing","option_c":"Move onto the left shoulder","option_d":"Drive beside the vehicle until it slows","correct_option":"A","explanation":"Do not race a vehicle that speeds up while being passed. Abandon the pass and return safely to your original lane.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Abandoning a pass","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":58,"question_text":"When may you pass a moving snow plow?","category":"Passing","option_a":"When its blue light is off","option_b":"Do not pass a moving snow plow","option_c":"Only on the right shoulder","option_d":"Whenever two lanes are available","correct_option":"B","explanation":"The handbook warns drivers not to pass moving snow plows because of their width, poor visibility and ridges of snow.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Snow-plow passing","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":59,"question_text":"How close to a pedestrian crossover is overtaking and passing prohibited?","category":"Passing Restrictions","option_a":"Within five metres","option_b":"Within 10 metres","option_c":"Within 30 metres","option_d":"Only while a pedestrian is visible","correct_option":"C","explanation":"Drivers must not overtake and pass another vehicle within 30 metres of a pedestrian crossover.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Pedestrian crossovers","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":60,"question_text":"Which statement about using the left shoulder to pass is correct?","category":"Passing on the Shoulder","option_a":"It is permitted when the shoulder is paved","option_b":"It is permitted to pass a left-turning vehicle","option_c":"It is permitted when traffic is moving below 30 km/h","option_d":"Passing on the left shoulder is prohibited, whether the shoulder is paved or not","correct_option":"D","explanation":"Drivers must not pass on the left shoulder, regardless of whether it is paved. The limited shoulder-passing exception applies only on the right for a left-turning vehicle when the shoulder is paved and the move is safe.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Left-shoulder prohibition","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":61,"question_text":"When reversing straight back or to the right, where should you look?","category":"Backing","option_a":"Turn your body and head to look back over your right shoulder","option_b":"Look only at the dashboard camera","option_c":"Use only the left side mirror","option_d":"Look forward and rely on sensors","correct_option":"A","explanation":"For a straight or right reverse, turn and look directly over the right shoulder while also checking the surrounding area.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Direct observation","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":62,"question_text":"Where is reversing generally illegal on a divided road?","category":"Backing","option_a":"On any road below 40 km/h","option_b":"On the travelled portion or shoulder of a divided road with a speed limit over 80 km/h, except to help someone in trouble","option_c":"Only inside a parking lot","option_d":"On every one-way street regardless of speed","correct_option":"B","explanation":"It is illegal to reverse on the travelled portion or shoulder of a divided road with a speed limit over 80 km/h, except when helping someone in trouble.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"High-speed divided roads","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":63,"question_text":"What minimum clear view is required in both directions before making a U-turn?","category":"U-Turns","option_a":"50 metres","option_b":"100 metres","option_c":"150 metres","option_d":"300 metres","correct_option":"C","explanation":"A U-turn may be made only where you can see at least 150 metres in both directions and no other restriction applies.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Required visibility","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":64,"question_text":"Which location is unsafe and illegal for a U-turn because the driver's view is obstructed?","category":"U-Turns","option_a":"A wide, straight road with a clear view","option_b":"A quiet cul-de-sac","option_c":"A marked turning basin","option_d":"On or near a curve, hilltop, railway crossing, bridge or tunnel that blocks the view","correct_option":"D","explanation":"Do not make a U-turn where a curve, hilltop, railway crossing, bridge or tunnel prevents the required clear view.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Prohibited locations","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":65,"question_text":"What is usually the simplest and safest way to reverse your direction after missing a turn?","category":"Turning Around","option_a":"Drive around the block","option_b":"Reverse along the roadway","option_c":"Make an immediate U-turn","option_d":"Stop and wait for traffic to go around","correct_option":"A","explanation":"Driving around the block is normally safer than making a U-turn or three-point turn.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Preferred turnaround","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":66,"question_text":"Does signalling a lane change give you the right-of-way?","category":"Lane Changes","option_a":"Yes, immediately","option_b":"No; you must still wait for a safe gap and yield to traffic already in the lane","option_c":"Only on roads with three or more lanes","option_d":"Only when moving left","correct_option":"B","explanation":"A signal communicates your intention but does not create a right-of-way. Change lanes only after confirming a safe gap.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Yielding during lane changes","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":67,"question_text":"How should you normally manage speed while moving into a safe gap during a lane change?","category":"Lane Changes","option_a":"Brake sharply while crossing the lane line","option_b":"Slow to half the traffic speed","option_c":"Maintain your speed or increase it gently to match traffic","option_d":"Accelerate as hard as possible","correct_option":"C","explanation":"Once the way is clear, steer gradually and maintain speed or increase it gently so your movement fits the traffic flow.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Speed matching","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":68,"question_text":"Where should unnecessary lane changes be especially avoided?","category":"Lane Changes","option_a":"On a long straight freeway","option_b":"After checking every blind spot","option_c":"When a lane is ending","option_d":"In or near an intersection","correct_option":"D","explanation":"Avoid changing lanes in or near intersections, where vehicle and pedestrian movements create additional conflicts.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Intersection conflicts","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":69,"question_text":"What should you do if you miss your intended exit in a roundabout?","category":"Roundabouts","option_a":"Continue around the roundabout and take the exit on the next circuit","option_b":"Stop and reverse","option_c":"Turn across the central island","option_d":"Change lanes abruptly toward the exit","correct_option":"A","explanation":"Never stop or reverse because you missed a roundabout exit. Continue around and approach the exit again safely.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Missed exits","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},
  {"authoring_id":70,"question_text":"When should you change lanes while circulating inside a roundabout?","category":"Roundabouts","option_a":"Whenever your exit is near","option_b":"Do not change lanes inside the roundabout","option_c":"Only beside a large truck","option_d":"Only without signalling","correct_option":"B","explanation":"Choose the correct lane before entering and maintain that lane through the roundabout. Do not change lanes while circulating.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Lane discipline","learning_topic":"Road position and manoeuvres","handbook_section":"Changing directions","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/changing-directions"},

  {"authoring_id":71,"question_text":"Why should you reduce speed before entering a curve at night?","category":"Night Driving","option_a":"Curves always have a lower legal limit","option_b":"High beams switch off automatically in every curve","option_c":"Headlights point mostly straight ahead, so less of the curved roadway may be visible","option_d":"Road markings cannot be seen on curves","correct_option":"C","explanation":"Because headlights illuminate mostly straight ahead, visibility through a curve is reduced. Slow before the curve so you can stop within the distance you can see.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Curves at night","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":72,"question_text":"Where should you direct your eyes to reduce glare from an approaching vehicle's headlights?","category":"Night Driving","option_a":"Directly at the headlights","option_b":"Into the rear-view mirror","option_c":"At the centre line immediately in front of you","option_d":"Slightly down and toward the right edge of your lane while keeping the road ahead in view","correct_option":"D","explanation":"Avoid staring at oncoming headlights. Look slightly down and to the right, using the right edge of the road as a guide.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Oncoming glare","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":73,"question_text":"What should you do if headlights from a vehicle behind you create glare in your rear-view mirror?","category":"Night Driving","option_a":"Use the mirror's night setting and avoid staring into the reflected light","option_b":"Aim the mirror directly back at the other driver","option_c":"Turn off your own headlights","option_d":"Brake suddenly to make the vehicle pass","correct_option":"A","explanation":"Use the rear-view mirror's day-night adjustment, if equipped, and keep your attention on the road instead of the reflected glare.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Rear glare","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":74,"question_text":"Which road reference should you use as a guide in dense fog?","category":"Fog Driving","option_a":"The headlights of an oncoming vehicle","option_b":"The right edge of the road","option_c":"The centre line","option_d":"The vehicle directly ahead at close distance","correct_option":"B","explanation":"Use the right edge of the roadway as a guide in fog. Following the centre line can draw you dangerously close to oncoming traffic.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Lane guidance","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":75,"question_text":"Why can a road be especially slippery when rain first begins?","category":"Rain Driving","option_a":"Tires immediately become overinflated","option_b":"Rain removes all pavement texture","option_c":"Water mixes with oil and dirt already on the road surface","option_d":"The road surface becomes colder than ice","correct_option":"C","explanation":"The first rain mixes with oil and dirt on the road, creating a particularly slippery surface.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"First rainfall","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":76,"question_text":"Why should you avoid driving through puddles when possible?","category":"Rain Driving","option_a":"They always contain salt","option_b":"They improve tire grip too quickly","option_c":"They cause headlights to switch off","option_d":"They may hide potholes, create dangerous spray, stall the engine or reduce brake effectiveness","correct_option":"D","explanation":"Puddles can conceal road damage, reduce visibility through spray, stall an engine and wet the brakes.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Standing water","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":77,"question_text":"What should you do first if your vehicle begins to hydroplane?","category":"Hydroplaning","option_a":"Ease off the accelerator and keep the steering steady","option_b":"Brake as hard as possible","option_c":"Turn sharply toward the shoulder","option_d":"Accelerate to push through the water","correct_option":"A","explanation":"Ease off the accelerator, hold the steering steady and avoid sudden braking or turning until the tires regain contact.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Recovery","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":78,"question_text":"What should you do when windshield wipers leave streaks that obstruct your view?","category":"Rain Driving","option_a":"Use the wipers only at high speed","option_b":"Replace the wiper blades","option_c":"Turn off the defroster","option_d":"Apply oil to the windshield","correct_option":"B","explanation":"Wiper blades that do not clean the windshield without streaking should be replaced so visibility is maintained.","difficulty_level":"easy","is_frequently_tested":false,"subcategory":"Wiper maintenance","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":79,"question_text":"Where is black ice likely to form first?","category":"Winter Driving","option_a":"Only in sunny open areas","option_b":"Only on gravel roads","option_c":"On bridges, overpasses and shaded sections of road","option_d":"Only where salt has been applied","correct_option":"C","explanation":"Bridges and overpasses cool from above and below, while shaded areas receive less warmth, so these locations often freeze first.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Black-ice locations","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":80,"question_text":"When is cruise control appropriate on a snow-covered road?","category":"Winter Driving","option_a":"When traffic is light","option_b":"When using winter tires","option_c":"Only while travelling downhill","option_d":"Never; cruise control should not be used in snow or other slippery conditions","correct_option":"D","explanation":"Cruise control can apply power at the wrong time when traction is poor, so do not use it on snow, ice or other slippery surfaces.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Cruise control","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":81,"question_text":"How should you perform emergency braking in a vehicle equipped with ABS?","category":"Anti-Lock Brakes","option_a":"Press the brake firmly and let ABS control wheel lock","option_b":"Pump the pedal rapidly","option_c":"Use the parking brake only","option_d":"Release the pedal whenever it pulsates","correct_option":"A","explanation":"With ABS, press the brake pedal firmly and continue steering as needed. Do not pump or release the brake because of pedal pulsation.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Emergency braking","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":82,"question_text":"What does pulsation in the brake pedal usually mean during hard braking with ABS?","category":"Anti-Lock Brakes","option_a":"The accelerator is stuck","option_b":"The ABS is operating normally","option_c":"Every tire has gone flat","option_d":"The parking brake is engaged","correct_option":"B","explanation":"Pedal pulsation is a normal sign that ABS is rapidly adjusting brake pressure to prevent wheel lock.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Pedal feedback","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":83,"question_text":"Which statement about ABS stopping distance is correct?","category":"Anti-Lock Brakes","option_a":"ABS always cuts stopping distance in half","option_b":"ABS makes stopping distance irrelevant","option_c":"ABS helps preserve steering control but does not guarantee a shorter stopping distance","option_d":"ABS increases traction beyond the tires' limits","correct_option":"C","explanation":"ABS prevents wheel lock and helps maintain steering control, but a driver should not expect it always to shorten stopping distance.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"System limitations","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":84,"question_text":"How is threshold braking performed in a vehicle without ABS?","category":"Threshold Braking","option_a":"Pump the pedal continuously","option_b":"Lock all wheels and hold them locked","option_c":"Use only the transmission","option_d":"Brake near the point of wheel lock, easing slightly if a wheel begins to lock, without pumping","correct_option":"D","explanation":"Threshold braking applies maximum pressure without locking the wheels. Ease slightly at lockup and reapply; do not pump the brakes.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"Non-ABS technique","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},
  {"authoring_id":85,"question_text":"What should you do when a whiteout reduces visibility to nearly zero?","category":"Whiteouts","option_a":"Get off the roadway into a safe parking area if possible","option_b":"Stop in the travelled lane","option_c":"Use high beams and continue at the speed limit","option_d":"Pass the vehicle ahead before stopping","correct_option":"A","explanation":"When visibility is near zero, try to leave the roadway and use a safe parking area. Do not stop in a travelled lane.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Near-zero visibility","learning_topic":"Weather and night driving","handbook_section":"Safe and responsible driving","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/safe-and-responsible-driving"},

  {"authoring_id":86,"question_text":"Why should you avoid raising the hood while waiting beside a disabled vehicle on a freeway?","category":"Freeway Breakdown","option_a":"It automatically drains the battery","option_b":"It can obstruct visibility and create an additional hazard","option_c":"It prevents hazard lights from working","option_d":"It causes the engine to restart","correct_option":"B","explanation":"On a high-speed roadside, a raised hood can obstruct visibility. Stay safely positioned and wait for professional assistance.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Roadside visibility","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":87,"question_text":"If pumping the brake pedal does not restore braking, how should the parking brake be used?","category":"Brake Failure","option_a":"Pull it as hard and fast as possible","option_b":"Do not use it under any circumstance","option_c":"Apply it gently but firmly while holding the release button","option_d":"Apply and release it repeatedly at high speed","correct_option":"C","explanation":"Apply the parking brake gently but firmly while holding its release so you can reduce force if the wheels begin to lock.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Parking-brake stop","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":88,"question_text":"If a stuck accelerator cannot be lifted with your foot, what should you do?","category":"Stuck Accelerator","option_a":"Reach down with both hands while moving","option_b":"Pump the accelerator harder","option_c":"Shift into a higher gear","option_d":"Turn on hazard lights, shift to neutral and stop safely off the road","correct_option":"D","explanation":"If the pedal cannot be freed with your foot, use hazard lights, shift to neutral and stop safely. Do not reach down with your hands while moving.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Neutral and safe stop","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":89,"question_text":"What should you do if your headlights fail at night and do not come back on after checking the switch?","category":"Headlight Failure","option_a":"Turn on hazard lights and stop safely off the road","option_b":"Continue using parking lights","option_c":"Follow another vehicle closely","option_d":"Drive on the shoulder until daylight","correct_option":"A","explanation":"If the headlights remain out, use hazard lights and bring the vehicle to a safe stop off the road. Do not continue driving without lights.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Safe stopping","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":90,"question_text":"At the first sign of vehicle trouble on a freeway, what should you do?","category":"Freeway Breakdown","option_a":"Wait for the vehicle to stall in a traffic lane","option_b":"Signal, turn on hazard lights and move to the nearest safe shoulder","option_c":"Stop immediately without checking mirrors","option_d":"Attempt repairs in the left lane","correct_option":"B","explanation":"Begin moving off the freeway at the first sign of trouble. Do not wait to stall in a live traffic lane.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Early pull-over","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":91,"question_text":"Where should you normally wait for help after your vehicle is safely disabled on a freeway shoulder?","category":"Freeway Breakdown","option_a":"Standing behind the vehicle","option_b":"Beside the driver's door","option_c":"Inside the vehicle with the doors locked","option_d":"In the nearest traffic lane","correct_option":"C","explanation":"Once safely off the road, remain in the locked vehicle while waiting for police or roadside assistance unless another immediate danger requires evacuation.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Waiting for assistance","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":92,"question_text":"What should you avoid if your wheels drop off the pavement?","category":"Off-Road Recovery","option_a":"Holding the steering wheel firmly","option_b":"Easing off the accelerator","option_c":"Keeping the vehicle straight while slowing","option_d":"Heavy braking or a sudden sharp return to the pavement","correct_option":"D","explanation":"Heavy braking or sudden steering can cause a loss of control. Slow gradually, regain control and return to the pavement smoothly.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Avoiding rollover","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":93,"question_text":"If you witness a serious collision and emergency officials have not arrived, what should you do when it is safe?","category":"Collision Assistance","option_a":"Stop in a safe place, call for help and offer reasonable assistance","option_b":"Continue without reporting it","option_c":"Block every traffic lane with your vehicle","option_d":"Move injured people immediately regardless of danger","correct_option":"A","explanation":"A witness should stop safely, summon emergency help and offer reasonable assistance without creating another hazard or acting beyond their training.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Witness response","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":94,"question_text":"When should an injured collision victim normally be moved?","category":"Collision Injuries","option_a":"Immediately, regardless of danger","option_b":"Only when necessary to protect the person from fire, explosion or another immediate danger","option_c":"Whenever traffic begins to slow","option_d":"Before emergency services are called","correct_option":"B","explanation":"Unless there is immediate danger such as fire, leave injured people where they are and wait for trained medical help.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Moving injured people","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":95,"question_text":"What should be done to reduce the risk of a second collision after a serious crash?","category":"Collision Scene Safety","option_a":"Leave all engines running","option_b":"Turn off all warning lights","option_c":"Turn off engines, use emergency flashers and warn approaching traffic when safe","option_d":"Stand in the traffic lane","correct_option":"C","explanation":"Secure the scene by turning off engines, activating emergency flashers and using safe warning methods for approaching traffic.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Scene protection","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":96,"question_text":"After a minor collision with no injuries, what should you do if the vehicles can be driven?","category":"Minor Collisions","option_a":"Leave them in the traffic lanes for photographs","option_b":"Abandon them and walk away","option_c":"Wait for a tow truck before changing position","option_d":"Move them as far off the road as possible when it is safe","correct_option":"D","explanation":"For a minor collision with no injuries, follow the Steer it, Clear it principle and move drivable vehicles out of traffic when safe.","difficulty_level":"easy","is_frequently_tested":true,"subcategory":"Steer it clear it","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":97,"question_text":"What information should drivers exchange after a collision involving damaged property?","category":"Collision Information","option_a":"Names, addresses, driver and vehicle details, plate and insurance information","option_b":"Only first names","option_c":"Only telephone numbers","option_d":"Banking and employment records","correct_option":"A","explanation":"Drivers must exchange identifying, driver, vehicle and insurance information with anyone whose vehicle or property was damaged.","difficulty_level":"medium","is_frequently_tested":true,"subcategory":"Required exchange","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":98,"question_text":"Why must smoking, matches and warning flares be kept away from a collision vehicle that may be leaking fuel?","category":"Collision Fire Safety","option_a":"They can damage the vehicle's battery","option_b":"They can ignite fuel vapour and cause a fire or explosion","option_c":"They interfere with police radios","option_d":"They make skid marks harder to see","correct_option":"B","explanation":"Fuel vapour may ignite. Keep cigarettes, matches and flares away from vehicles when a fuel leak is possible.","difficulty_level":"hard","is_frequently_tested":true,"subcategory":"Fuel-leak precautions","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":99,"question_text":"How can an untrained helper assist a conscious collision victim who may be in shock while waiting for emergency services?","category":"First Aid","option_a":"Give the person food immediately","option_b":"Ask the person to walk around","option_c":"Keep the person warm with a jacket or blanket and provide reassurance","option_d":"Move the person into another vehicle","correct_option":"C","explanation":"If there is no immediate danger, keep the injured person still, warm and reassured until trained help arrives.","difficulty_level":"medium","is_frequently_tested":false,"subcategory":"Shock care","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"},
  {"authoring_id":100,"question_text":"How should a driver with first-aid training treat injuries at a collision scene?","category":"First Aid","option_a":"Treat only minor cuts before calling for help","option_b":"Move every injured person before treatment","option_c":"Attempt procedures beyond their training","option_d":"Treat injuries in order of urgency and only within the level of their training","correct_option":"D","explanation":"After ensuring scene safety and calling for help, a trained person should treat the most urgent injuries first and stay within their training.","difficulty_level":"hard","is_frequently_tested":false,"subcategory":"Treatment priorities","learning_topic":"Emergencies and collisions","handbook_section":"Dealing with emergencies","handbook_url":"https://www.ontario.ca/document/official-mto-drivers-handbook/dealing-emergencies"}
]
$question_bank$::jsonb) as q(
  authoring_id integer,
  question_text text,
  category text,
  option_a text,
  option_b text,
  option_c text,
  option_d text,
  correct_option text,
  explanation text,
  difficulty_level text,
  is_frequently_tested boolean,
  subcategory text,
  learning_topic text,
  handbook_section text,
  handbook_url text
);

do $$
declare
  issue_count integer;
begin
  if (select count(*) from new_rules_question_batch) <> 100 then
    raise exception 'Expected exactly 100 authored rules questions';
  end if;

  if (select count(distinct lower(question_text)) from new_rules_question_batch) <> 100 then
    raise exception 'Authored rules questions contain duplicate question text';
  end if;

  select count(*) into issue_count
  from new_rules_question_batch q
  where q.authoring_id not between 1 and 100
     or q.correct_option not in ('A', 'B', 'C', 'D')
     or q.difficulty_level not in ('easy', 'medium', 'hard')
     or cardinality(array[
       lower(btrim(q.option_a)), lower(btrim(q.option_b)),
       lower(btrim(q.option_c)), lower(btrim(q.option_d))
     ]) <> 4
     or (select count(distinct option_value) from unnest(array[
       lower(btrim(q.option_a)), lower(btrim(q.option_b)),
       lower(btrim(q.option_c)), lower(btrim(q.option_d))
     ]) option_value) <> 4
     or btrim(q.question_text) = ''
     or btrim(q.explanation) = ''
     or btrim(q.subcategory) = ''
     or btrim(q.learning_topic) = ''
     or btrim(q.handbook_section) = ''
     or q.handbook_url !~ '^https://www[.]ontario[.]ca/';

  if issue_count <> 0 then
    raise exception 'Authored rules questions failed structural validation: % issue(s)', issue_count;
  end if;

  if exists (
    select 1
    from (
      select correct_option, count(*) as answer_count
      from new_rules_question_batch
      group by correct_option
    ) distribution
    where answer_count <> 25
  ) then
    raise exception 'Correct-answer positions must contain exactly 25 questions each';
  end if;

  if exists (
    select 1
    from new_rules_question_batch authored
    join public.rules_questions existing
      on lower(btrim(existing.question_text)) = lower(btrim(authored.question_text))
  ) then
    raise exception 'One or more authored questions already exist in rules_questions';
  end if;
end
$$;

insert into public.rules_questions (
  question_text,
  category,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  difficulty_level,
  is_frequently_tested,
  is_active,
  subcategory,
  learning_topic,
  handbook_section,
  handbook_url
)
select
  question_text,
  category,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  difficulty_level,
  is_frequently_tested,
  true,
  subcategory,
  learning_topic,
  handbook_section,
  handbook_url
from new_rules_question_batch
order by authoring_id;

do $$
begin
  if (
    select count(*)
    from public.rules_questions existing
    join new_rules_question_batch authored
      on lower(btrim(existing.question_text)) = lower(btrim(authored.question_text))
    where existing.is_active = true
  ) <> 100 then
    raise exception 'Not all 100 authored rules questions were inserted as active records';
  end if;
end
$$;

commit;
